export const proposals = [
  {
    id: 1,
    proposalName: "Proposal 1",
    developmentSector: "Sector 1",
    states: ["State 1", "State 2"],
    company: "Company 1",
  },
  {
    id: 2,
    proposalName: "Proposal 2",
    developmentSector: "Sector 2",
    states: ["State 3"],
    company: "Company 2",
  },
  {
    id: 3,
    proposalName: "Proposal 3",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 3",
  },
  {
    id: 4,
    proposalName: "Proposal 4",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 4",
  },
  {
    id: 5,
    proposalName: "Proposal 5",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 5",
  },
  {
    id: 6,
    proposalName: "Proposal 6",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 6",
  },
  {
    id: 7,
    proposalName: "Proposal 7",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 7",
  },
  {
    id: 8,
    proposalName: "Proposal 7",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 8",
  },
  {
    id: 9,
    proposalName: "Proposal 7",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 9",
  },
  {
    id: 10,
    proposalName: "Proposal 7",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 10",
  },
  {
    id: 11,
    proposalName: "Proposal 7",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 11",
  },
  {
    id: 12,
    proposalName: "Proposal 7",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 12",
  },
  {
    id: 13,
    proposalName: "Proposal 7",
    developmentSector: "Sector 3",
    states: ["State 4", "State 5", "State 6"],
    company: "Company 13",
  },
];
